### ISSUE TITLE
调度器BUG

### ISSUE THREAD

**Issue by zhilulingguan** [lmooml/SmartTimer#1]
415行，uint32_t 数据类型溢出比较应当是0xffffffff

**Comment by lmooml** [comment]
我又复活了，才看到。
已经改过来了，感谢！

**Comment by zhilulingguan** [comment]
stim_tick函数中，对时间链表重新调整后访问新的节点的下一个事件，造成老节点与新节点之间的事件被遗漏。我不知道您在插入事件链表的时候比较了下一次的时间大小，这样可以重新按照时间顺序排列链表，这样是为了节省资源吗。所以我按照这个想法对stim_tick时间做了如下更改。单行注释之间的内容是新添加的
/*
 * ===  FUNCTION  ======================================================================
 *         Name:  stim_tick
 *  Description:  engine of smarttimer.
 *                It must be execute in systick( or hardware timer) interrupt
 * =====================================================================================
 */
void stim_tick (void)
{
  struct stim_event *event;
  struct stim_event *last_event = NULL;
  struct stim_event_list *list;
  uint8_t temp_flag = 0;

  if(((current_tick + 1) & UINT32_MAX) < current_tick){
    list_manager.cur_index ^= 0x01;
  }
  current_tick++;

  list = &list_manager.list[list_manager.cur_index];
  event = list->head;
  //
  while(event != NULL && event->tick_punch <= current_tick){
    if(event->next != NULL)event = event->next;
    else 
    {
      temp_flag = 1;
      break;
    }
  }
  if((event->prev != NULL) && (temp_flag != 1)) event = event->prev;
  //
  while(event != NULL && event->tick_punch <= current_tick){
    mark_list[event->id] += 1;



    if((event->looptimes != STIM_LOOP_FOREVER) && 
        (--event->looptimes == 0)){
      event->stat = STIM_EVENT_RECYCLE;
      last_event = event->prev;
      recyle_event(event);
      event = last_event;
    }else{
      event->tick_punch = current_tick + event->interval;
      remove_node(event,list);
      if(event->tick_punch < current_tick){
        list = &list_manager.list[list_manager.cur_index ^ 0x01];
      }
      insert_event(event,list);
      //
      event = event->prev;
      //
    }
    //event = event->next;
    
  }

}		/* -----  end of function stim_dispach  ----- */
